### ISSUE TITLE
Transparent backgrounds lead to black background in jpegs

### ISSUE THREAD

**Issue by samlising** [spacecatninja/craft-imager-x-pdf-adapter#1]
It seems that Imagick does not see the background color of many PDF files. 
If generating a png the background will be transparent. If generating a jpg the back ground will be black.

I was able to resolve this by adding Flatten Layers and setting the colorspace to sRGB.

I added 2 lines to the PDF.php file in the plugin. They should follow immediately after the readimage line.
```
$im->readimage($this->sourceModel->getFilePath().'['.($this->page - 1).']');
$im = $im->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);
$im->transformImageColorspace(\Imagick::COLORSPACE_SRGB);
```

Is it possible to add this to your next update. 

Thanks.

**Comment by aelvan** [comment]
Hi, 

The background color that should be used when converting to jpeg can be controlled using [`bgColor`](https://imager-x.spacecat.ninja/configuration.html#bgcolor-string) in Imager.

Doesn't that solve the issue, or does your proposed fix have any additional benefits?
