### ISSUE TITLE
Transformers expect $image to be type Asset not PDF

### ISSUE THREAD

**Issue by jamiepittock** [spacecatninja/craft-imager-x-pdf-adapter#3]
Hi - 

How many Imager transformers actually support adapters like this? We use Servd and their transformer throws an error because it was expecting `$image` to be of type `Asset` and we sent a `PDF`.

I checked some of the other transformers and they all look like they'll have the same issue.

**Comment by aelvan** [comment]
Sorry, I missed this. It's up to the transformer to support it somehow, from my end it has only been added to the `craft` transformer so far. But it's worth nothing that alot of other services, like imgix and Imagekit, already have support for transforming PDFs directly without the need for any intermediate layer. I'm not familiar with servd, so I can't say if that's the case there.
